title: minhloc Blog
description: Product Reviews, Tech Insights, and Market Analysis
baseurl: "/seo.github.io"
url: "https://minhloc-2002.github.io"

author:
  name:  minhloc
  bio: >
    hi
  email: martinkimberlyfegae5011@gmail.com
  twitter: Martinkimb54669

theme: minima

markdown: kramdown

permalink: /:title/

collections:
  posts:
    output: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
